"""Data-fetching for the interaction_summary intent. The actual summary
text is generated by the LLM in the node — this just assembles the
context (the interaction plus recent history with the same doctor)."""

import uuid

from sqlalchemy.orm import Session

from app.models.interaction import Interaction
from app.services import interaction_service


def get_interaction_with_history(db: Session, interaction_id: uuid.UUID) -> tuple[Interaction, list[Interaction]]:
    interaction = interaction_service.get_interaction(db, interaction_id)
    recent, _ = interaction_service.get_doctor_timeline(db, interaction.doctor_id, page=1, page_size=10)
    history = [item for item in recent if item.id != interaction.id]
    return interaction, history
