"""add ai-first interaction fields

Revision ID: b80d652fcce5
Revises: 0e22df8c32e3
Create Date: 2026-07-12 14:22:45.609530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80d652fcce5'
down_revision: Union[str, Sequence[str], None] = '0e22df8c32e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('attendees', sa.String(length=300), nullable=True))
    op.add_column('interactions', sa.Column('topics_discussed', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('clinical_evidence', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('questions_raised', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('objections', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('competitor_discussion', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('promotional_materials', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('brochures_shared', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('interest_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='interest_level', native_enum=False), nullable=True))
    op.add_column('interactions', sa.Column('next_best_action', sa.Text(), nullable=True))
    op.add_column('interactions', sa.Column('ai_summary', sa.Text(), nullable=True))
    # NOT NULL with a server_default so the ALTER succeeds against the
    # existing rows already in this table (autogenerate doesn't add one).
    op.add_column('interactions', sa.Column('ai_suggestions', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('interactions', sa.Column('missing_information', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('interactions', sa.Column('confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'confidence_score')
    op.drop_column('interactions', 'missing_information')
    op.drop_column('interactions', 'ai_suggestions')
    op.drop_column('interactions', 'ai_summary')
    op.drop_column('interactions', 'next_best_action')
    op.drop_column('interactions', 'interest_level')
    op.drop_column('interactions', 'brochures_shared')
    op.drop_column('interactions', 'promotional_materials')
    op.drop_column('interactions', 'competitor_discussion')
    op.drop_column('interactions', 'objections')
    op.drop_column('interactions', 'questions_raised')
    op.drop_column('interactions', 'clinical_evidence')
    op.drop_column('interactions', 'topics_discussed')
    op.drop_column('interactions', 'attendees')
    # ### end Alembic commands ###
