"""
Declarative base shared by every model. The naming convention gives
Alembic-generated constraints predictable names (e.g. `fk_interactions_
doctor_id_doctors` instead of an autogenerated `fk_interactions_doctor_id_
doctors_abc123`), which matters once you need to reference one in a
future migration.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
